### ISSUE TITLE
Automatic binaries from Travis aren't working

### ISSUE THREAD

**Issue by tshort** [JuliaDiffEq/SundialsBuilder#2]
`.travis.yml` needs to be updated. A new key needs to be created, too. For 3.1.0-1, I uploaded the binaries manually.

**Comment by ChrisRackauckas** [comment]
For reference, how are you building the binaries right now then?

**Comment by tshort** [comment]
On a Linux box (or virtual machine), run the script [build_tarballs.jl](https://github.com/JuliaDiffEq/SundialsBuilder/blob/master/build_tarballs.jl). 
This builds libraries for all platforms and put them in a folder `products`. It also prints out a version of `build.jl` for updating Sundials (particularly [these](https://github.com/JuliaDiffEq/Sundials.jl/blob/master/deps/build.jl#L45-L52) lines).

Adjust `build_tarballs.jl` as needed. For more exploratory work, you can run `BinaryBuilder.run_wizard()` to get a shell prompt in the builder environment.

**Comment by ChrisRackauckas** [comment]
I'll give it a go right now. You don't need to be on Windows or Mac to generate those binaries?

**Comment by ChrisRackauckas** [comment]
Cool, I'm trying it out now. I'll try adding the flag.

**Comment by ChrisRackauckas** [comment]
How do you add the products to a release?

**Comment by tshort** [comment]
Draft or edit a release and drag and drop the files to the box on that page.

**Comment by ChrisRackauckas** [comment]
Oh, the old fashion way 👍 .

What was wrong with the Travis part? It looks like it builds correctly?

**Comment by tshort** [comment]
If Travis is working, when you tag a new release of SundialsBuilder, Travis will build all of the libraries and upload them to the release.

**Comment by tshort** [comment]
In addition to fixing the links in `.travis.yml`, I think a github OAuth key may need to be generated. I'm not quite sure because the wizard did all of that automatically.
