### ISSUE TITLE
KLU build

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SundialsBuilder#3]
@tshort

I can't find out what's going on with the KLU build. It says

```
[11:09:06] CMake Warning at config/SundialsCMakeMacros.cmake:83 (MESSAGE):
[11:09:06]   ------------------------------------------------------------
[11:09:06] 
[11:09:06]   WARNING: KLU LIBRARIES NOT Found.  Please check library path
[11:09:06] 
[11:09:06]   /workspace/wqDihVXA/srcdir/SuiteSparse/KLU/Lib
[11:09:06] 
[11:09:06]   ------------------------------------------------------------
```

but when I add 

```
echo 1
ls $WORKSPACE/destdir/lib
echo 2
ls $WORKSPACE/srcdir/SuiteSparse/KLU/Lib
``` 

I get:

```
[11:09:05] 1
[11:09:05] libamd.2.4.6.dll
[11:09:05] libamd.2.dll
[11:09:05] libamd.dll
[11:09:05] libbtf.1.2.6.dll
[11:09:05] libbtf.1.dll
[11:09:05] libbtf.dll
[11:09:05] libcolamd.2.9.6.dll
[11:09:05] libcolamd.2.dll
[11:09:05] libcolamd.dll
[11:09:05] libklu.1.3.8.dll
[11:09:05] libklu.1.dll
[11:09:05] libklu.dll
[11:09:05] libsuitesparseconfig.5.0.0.dll
[11:09:05] libsuitesparseconfig.5.dll
[11:09:05] libsuitesparseconfig.dll
[11:09:05] 2
[11:09:05] Makefile
[11:09:05] klu_analyze.o
[11:09:05] klu_analyze_given.o
[11:09:05] klu_d.o
[11:09:05] klu_d_diagnostics.o
[11:09:05] klu_d_dump.o
[11:09:05] klu_d_extract.o
[11:09:05] klu_d_factor.o
[11:09:05] klu_d_free_numeric.o
[11:09:05] klu_d_kernel.o
[11:09:05] klu_d_refactor.o
[11:09:05] klu_d_scale.o
[11:09:05] klu_d_solve.o
[11:09:05] klu_d_sort.o
[11:09:05] klu_d_tsolve.o
[11:09:05] klu_defaults.o
[11:09:05] klu_free_symbolic.o
[11:09:05] klu_l.o
[11:09:05] klu_l_analyze.o
[11:09:05] klu_l_analyze_given.o
[11:09:05] klu_l_defaults.o
[11:09:05] klu_l_diagnostics.o
[11:09:05] klu_l_dump.o
[11:09:05] klu_l_extract.o
[11:09:05] klu_l_factor.o
[11:09:05] klu_l_free_numeric.o
[11:09:05] klu_l_free_symbolic.o
[11:09:05] klu_l_kernel.o
[11:09:05] klu_l_memory.o
[11:09:05] klu_l_refactor.o
[11:09:05] klu_l_scale.o
[11:09:05] klu_l_solve.o
[11:09:05] klu_l_sort.o
[11:09:05] klu_l_tsolve.o
[11:09:05] klu_memory.o
[11:09:05] klu_z.o
[11:09:05] klu_z_diagnostics.o
[11:09:05] klu_z_dump.o
[11:09:05] klu_z_extract.o
[11:09:05] klu_z_factor.o
[11:09:05] klu_z_free_numeric.o
[11:09:05] klu_z_kernel.o
[11:09:05] klu_z_refactor.o
[11:09:05] klu_z_scale.o
[11:09:05] klu_z_solve.o
[11:09:05] klu_z_sort.o
[11:09:05] klu_z_tsolve.o
[11:09:05] klu_zl.o
[11:09:05] klu_zl_diagnostics.o
[11:09:05] klu_zl_dump.o
[11:09:05] klu_zl_extract.o
[11:09:05] klu_zl_factor.o
[11:09:05] klu_zl_free_numeric.o
[11:09:05] klu_zl_kernel.o
[11:09:05] klu_zl_refactor.o
[11:09:05] klu_zl_scale.o
[11:09:05] klu_zl_solve.o
[11:09:05] klu_zl_sort.o
[11:09:05] klu_zl_tsolve.o
[11:09:05] libklu.lib
```

I assume I want the latter? I tried both and it didn't work.

**Comment by tshort** [comment]
I'll give it a try tonight, too.

@MartinOtter, just a heads up. The libraries I gave you likely don't work with KLU. We're still trying to get the build to work. The regular Sundials build without KLU is integrated pretty well now.

**Comment by ChrisRackauckas** [comment]
The Sundials manual says we should be using SuiteSparse 4.5.3, so I backed that up but I can't even get klu on that version to build locally.

**Comment by tshort** [comment]
I played with it for a bit and got stuck. I tried digging into the cmake
files to see why it's erroring. There are `find_library` functions that are
coming up empty, but I couldn't figure out why.

**Comment by smldis** [comment]
Ok, different sources say that linking intel-TBB is the problem and they add patches https://github.com/saketkc/homebrew-science/blob/51eea3a288fb7de0907e649eb6623ef093429496/suite-sparse.rb https://www.mail-archive.com/arch-commits@archlinux.org/msg367184.html

I am trying BinaryBuilder and joining the effort to get evreything built.

**Comment by tshort** [comment]
I tried this build script on an Arch Linux box, and Sundials found the KLU libraries fine.

In the build environment, it can't find the libraries. The `find_library` functions are returning `NOT_FOUND`.  In the build environment, `CMAKE_FIND_LIBRARY_PREFIXES` is `lib`, and `CMAKE_FIND_LIBRARY_SUFFIXES` is `.so.a`. Both of those seem right. `KLU_LIBRARY_NAME` and `KLU_LIBRARY_DIR` both seem right. I don't know what else to check.

**Comment by ChrisRackauckas** [comment]
Is there something about the build environment that we don't know about? Probably overusing this, but @staticfloat might be able to give some input on that.

**Comment by staticfloat** [comment]
Hmmm, we should try figuring out all the different reasons that CMake might reject the library.  E.g. maybe it's finding it, but rejecting it because it is.........built for the wrong architecture?  (32bit/64bit differences?) Also, how are you providing the library path to CMake?

**Comment by tshort** [comment]
Here's where I think cmake is getting tripped up (in `config/FindKLU.cmake`):

```
    # find library with user provided directory path
    set(KLU_LIBRARY_NAME klu)
    find_library(KLU_LIBRARY ${KLU_LIBRARY_NAME} ${KLU_LIBRARY_DIR} NO_DEFAULT_PATH)
```
I printed out `KLU_LIBRARY_NAME` and `KLU_LIBRARY_DIR`, and those both seem right. I don't know how to debug other issues like 32/64-bit differences. `KLU_LIBRARY` becomes set as `KLU_LIBRARY-NOTFOUND`, so it suggests that cmake can't find it.

**Comment by tshort** [comment]
I just tried running cmake and directly setting `KLU_LIBRARY`, `BTF_LIBRARY`, and all of the other SuiteSparse libraries needed. With this, cmake completed without errors, and the "Checking of KLU" comes back OK. The `make` invocation seems to be working, too.

This could be a work-around, but we'd have to account for platform differences in setting all of the `KLU_LIBRARY` environment variables.

**Comment by smldis** [comment]
Nice, actually the docs say to set them directly:
see page 183 of https://computation.llnl.gov/sites/default/files/public/cv_guide.pdf

I don't have binary builder due to some issues with my os, but I was preparing the build script for Suite Sparse and this is what I came up with:
```

cd $WORKSPACE/srcdir

cat > suitesparse-link-tbb.patch <<'END'
--- SuiteSparse/SPQR/Lib/Makefile.orig	2016-09-24 09:36:59.588640845 +0000
+++ SuiteSparse/SPQR/Lib/Makefile	2016-09-24 09:37:14.248588339 +0000
@@ -13,7 +13,7 @@
 include ../../SuiteSparse_config/SuiteSparse_config.mk
 
 # SPQR depends on CHOLMOD, AMD, COLAMD, LAPACK, the BLAS and SuiteSparse_config
-LDLIBS += -lamd -lcolamd -lcholmod -lsuitesparseconfig $(LAPACK) $(BLAS)
+LDLIBS += -lamd -lcolamd -lcholmod -lsuitesparseconfig $(LAPACK) $(BLAS) $(TBB)
 
 # compile and install in SuiteSparse/lib
 library:
END

patch -l SuiteSparse/SPQR/Lib/Makefile < suitesparse-link-tbb.patch

cd SuiteSparse/

# run make config for options list

BLAS=-lblas TBB=-ltbb SPQR_CONFIG=-DHAVE_TBB make

BLAS=-lblas TBB=-ltbb SPQR_CONFIG=-DHAVE_TBB \
    make INSTALL_LIB=$WORKSPACE/destdir/usr/lib INSTALL_INCLUDE=$WORKSPACE/destdir/include install

# fix RPATH
chrpath -d $WORKSPACE/destdir/usr/lib/*
```

To which blas and tbb are you linking to? 
It seems that if we need to link to a BLAS lib, we can install OpenBLAS as provided by `OpenBLASBuilder`.
Intel-TBB as a dependency is optional, it is used by SuiteSparseQR, do we have the same problem with this dependency?

**Comment by ChrisRackauckas** [comment]
I am not sure we need a BLAS lib for KLU, though we will want it for SuperLUMT anyways.

**Comment by tshort** [comment]
I also think KLU doesn't need BLAS.

On the Sundials docs, I read that differently. It says "The CMake configure will result in populating the following variables: AMD_LIBRARY_DIR, BTF_LIBRARY, BTF_LIBRARY_DIR, COLAMD_LIBRARY, COLAMD_LIBRARY_DIR, and KLU_LIBRARY." Those are the ones I explicitly set, and I don't think that's how you're supposed to do it.

**Comment by smldis** [comment]
Ah ok I see, you are relying on setting the results explicitly. 
I checked, BLAS is needed for UMFPACK and CHOLMOD, for KLU it is not listed in the readme as a dependency.

**Comment by tshort** [comment]
@ChrisRackauckas, do you have a test example that uses KLU that I could try? I could see if my work-around build actually works.

**Comment by ChrisRackauckas** [comment]
No I don't have one because I haven't tried to make the wrapper part for that because I haven't been able to build a version with it yet. You'd have to ccall in for the linear solver.

**Comment by smldis** [comment]
I guess you can try running the sundials examples. For example:
https://github.com/LLNL/sundials/blob/master/examples/idas/serial/idasRoberts_ASAi_klu.c

**Comment by ChrisRackauckas** [comment]
That stuff wouldn't be wrapped by the Clang.jl wrapper though because it wasn't wrapped when I ran `wrap_sundials.jl`, so you'd need to ccall to do the KLU-specific commands.

**Comment by ChrisRackauckas** [comment]
@tshort do you have binaries I can try? I can work on the wrapper if you have binaries, and then the binary builder will be easier to test.

**Comment by tshort** [comment]
I had some binaries inside the wizard, Chris. I’ll recreate and save them.

**Comment by tshort** [comment]
@ChrisRackauckas, see the following for binaries:

https://github.com/JuliaDiffEq/SundialsBuilder/releases/tag/klu-workaround-0.0.1

**Comment by ChrisRackauckas** [comment]
That worked. The klu branch updates to work with and test it.

**Comment by tshort** [comment]
I'm not sure what to do here. The workaround seems to work, but it's a big kludge.

I played around with this more, but I can't get KLU built the "right way." In the builder environment, the cmake script runs right if I leave off  `-DCMAKE_TOOLCHAIN_FILE=/opt/$target/$target.toolchain` in the cmake invokation.

With the toolchain reference included, `find_library` within the cmake script fails for all of the KLU components.

**Comment by tshort** [comment]
The problem is from the `set(CMAKE_SYSROOT ..)` directive in the toolchain file. Without that, it works.

**Comment by tshort** [comment]
A bit closer... With the following added to the cmake call, it mostly works:

```
-DCMAKE_FIND_ROOT_PATH=$WORKSPACE/destdir
```

Windows is broken, though. KLU isn't building right.

**Comment by tshort** [comment]
Here's another try with a cleaner build script:

https://github.com/JuliaDiffEq/SundialsBuilder/releases/tag/klu-workaround-0.0.2

Hopefully, this "just works". There were some scary-looking warnings for 32 bit, but hopefully 64-bit builds work.

**Comment by ChrisRackauckas** [comment]
Here's the working branch:

https://github.com/JuliaDiffEq/Sundials.jl/pull/155/files#diff-ed74277d7f2e98f12cf51e6b8be90705

Last time all but Win32 passed.

**Comment by tshort** [comment]
Am I reading this right?

- Tests pass on Linux64 and Win64.
- Mac fails on one arkode test.
- Win32 fails.

So, the Mac failure is new.

**Comment by ChrisRackauckas** [comment]
The Mac failure is likely just a tolerance thing. I'll look into that but that's unrelated to any of the changes in the PR. Win32 is failing though: is it setting the Sundials indexing type correctly?

**Comment by tshort** [comment]
In the Win32 build of Sundials, it finds KLU okay. It shows several warnings like the following in the `sundials_sunlinsolspgmr_shared` build:

```
[11:23:39] /workspace/KlCcu2D0/srcdir/sundials-3.1.0/src/sunlinsol_klu/sunlinsol_klu.c: In function ‘SUNKLU’:
[11:23:39] /workspace/KlCcu2D0/srcdir/sundials-3.1.0/src/sunlinsol_klu/sunlinsol_klu.c:122:25: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
[11:23:39]      content->klu_solver = &klu_l_solve;
[11:23:39]                          ^
[11:23:39] /workspace/KlCcu2D0/srcdir/sundials-3.1.0/src/sunlinsol_klu/sunlinsol_klu.c:124:25: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
[11:23:39]      content->klu_solver = &klu_l_tsolve;
[11:23:39]                          ^
[
```

**Comment by tshort** [comment]
Here's where SuiteSparse defines integer sizes:

https://github.com/sergiud/SuiteSparse/blob/master/SuiteSparse_config/SuiteSparse_config.h#L8-L68

Julia also patches this [here](https://github.com/JuliaLang/julia/blob/master/deps/patches/SuiteSparse-winclang.patch). I tried adding this patch, and I still got the errors above on the 32-bit windows part of the build.

I'm not sure what to try next.

**Comment by ChrisRackauckas** [comment]
Sundials is using 32-bit integers for its indexing type on Win32 with the current build script on master. It looks like yours is failing long before it ever uses KLU: are you sure it's setting the indexing type correctly?

**Comment by ChrisRackauckas** [comment]
Hmm that's odd then, since it should work fine until KLU is called?

**Comment by tshort** [comment]
Yes, it's odd. That's what I'd expect. 

Maybe I goofed something on the uploads. I could just try a redo. (Long shot)

**Comment by tshort** [comment]
I just uploaded another build try with KLU. Turns out the `-DSUNDIALS_INDEX_TYPE=int32_t` wasn't getting hit.

**Comment by ChrisRackauckas** [comment]
Tests pass! 👍 . Merging when they all complete. Can you update the build script?

**Comment by tshort** [comment]
Great. I see that you already updated the build script in Sundials. To button this up, I was hoping to do the following:

* Merge cmake-mod branch.

* Rename the `klu-workaround-0.0.3` release to ` sundials-3.1.0-3`.

* Delete most of the "junk" releases. Is that okay, @ChrisRackauckas?

Anything else?

**Comment by ChrisRackauckas** [comment]
I don't think we should delete releases, at least for awhile, since there are versions of Sundials using some of them. After Pkg3's update the old tags just won't carry over and we can delete the cruft.

**Comment by tshort** [comment]
Okay, I'll leave the old releases in there. Note that I did rename the latest release as `sundials-3.1.0-3`. Sundials will need to be updated before it is tagged.

**Comment by ChrisRackauckas** [comment]
It was already tagged... did it cause this? https://discourse.julialang.org/t/has-mismatch-on-latest-sundials/9128

**Comment by tshort** [comment]
You're too fast on the trigger, Chris! I only renamed it ten minutes ago, so I doubt that's the problem. Anyway, suggestions?

**Comment by ChrisRackauckas** [comment]
Suggestions for?

I updated the Sundials deps file and will tag after tests pass. I guess that bug is just the MacOS bug and we can't do much there because it's a BinaryProvider.jl thing.

**Comment by tshort** [comment]
I was just wondering if I needed to re-rename the release. But, I guess you're still two steps ahead of me 😄.

**Comment by tshort** [comment]
I haven't been following the BinaryProvider issue on macOS. I guess we can re-run when that's sorted out.

**Comment by ChrisRackauckas** [comment]
That's my bad, I probably should've tagged you with the commit. No big deal. It looks like Github keeps the old tag but not the release, so it's still fixed. Deleting tags is hard.

**Comment by ChrisRackauckas** [comment]
>I haven't been following the BinaryProvider issue on macOS. I guess we can re-run when that's sorted out.

If you update on MacOS, both binaries exist and it chooses one in the folder (at random?) to check the hash with or something like that. It's only an update issue and only MacOS.

**Comment by tshort** [comment]
Thx.

**Comment by tshort** [comment]
@MartinOtter, the KLU integration with Sundials.jl is done. It gets you binary libraries of Sundials 3.1.0 with KLU on all the major Julia platforms: Windows, macOS, Linux, plus a few others, and it has 32- and 64-bit versions for Windows and Linux. 

I'm interested in hearing if it works with Modia. Supporting Modia was my main motivation for integrating KLU.

**Comment by MartinOtter** [comment]
This is really great!!! I will try to switch Modia to this Sundials version in the next 1-2 weeks and will report how this works with my test models. I will also try to add some (non-Modia) test models your Sundials distribution

**Comment by tshort** [comment]
@MartinOtter, any updates on Sundials/KLU and Modia?
