### ISSUE TITLE
SuperLUMT build

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SundialsBuilder#4]
I think the last short term goal should be building with SuperLUMT. This will require using OpenBLAS builder to then build SuperLUMT, but other than that most of the details for how to wrap are known. @tshort have you looked into this one at all?

**Comment by ChrisRackauckas** [comment]
https://github.com/davidanthoff/ReadStatBuilder/blob/master/build_tarballs.jl#L44-L48

You just add a dependency to add a separate builder.

**Comment by tshort** [comment]
I haven't looked before, but I took a quick look. Some of the issues with building incluce:

* MT is the parallel version, so it wants OpenMP or Pthreads or something.
* It's Fortran.
* You likely have to modify the 'Make.inc' for different targets.

That's enough to scare me off for now.

**Comment by ChrisRackauckas** [comment]
Okay, then let's put that off with the rest of parallelism. That's good to know. Thanks for checking it out, this is a good spot!

**Comment by ChrisRackauckas** [comment]
BTW, I made that a GSoC. We'll see if there's any takers. Maybe a few years down the line a student will be interested and we can pick this up again.

https://julialang.org/soc/projects/diffeq.html#parallelization-of-the-sundials-solver-library
